### ISSUE TITLE
Installation a bit arduous

### ISSUE THREAD

**Issue by sleepysnapdragon** [fac18/week3-DFJL-bday-time-machine#40]
Good attention to security, and the installation contained all the steps needed to set up.  If it's possible to walkthrough how to get the keys for each API that might save a bit of time - took me about 15 minutes just to do that which was a bit frustrating!

**Comment by nikkesan** [comment]
similar to issue #39 
Apparently there's a way to get around this to create your own environmental controls which we will luckily learn about next week when we host our own server!
